// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vivarium.Api.Data;

#nullable disable

namespace Vivarium.Api.Data.Migrations
{
    [DbContext(typeof(VivariumDbContext))]
    [Migration("20260730132306_AddBreeding")]
    partial class AddBreeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vivarium.Core.Domain.BreedingSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChildCreatureId")
                        .HasColumnType("bigint");

                    b.Property<long>("HabitatId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentAId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentBId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChildCreatureId");

                    b.HasIndex("HabitatId");

                    b.HasIndex("ParentAId");

                    b.HasIndex("ParentBId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("BreedingSlots");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.CreatureInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("HabitatId")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentAId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentBId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RarityScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("TraitConfigVersion")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HabitatId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentAId");

                    b.HasIndex("ParentBId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("CreatureInstances");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.CurrencyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CurrencyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SOFT",
                            Name = "Moeda Soft"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PREMIUM",
                            Name = "Moeda Premium"
                        });
                });

            modelBuilder.Entity("Vivarium.Core.Domain.GenerationQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("HabitatId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSick")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("HabitatId", "Status");

                    b.ToTable("GenerationQueueItems");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.Habitat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("CoinAccrual")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenerationIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("GenerationProgressMinutes")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("HabitatTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastTickAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaintenanceLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("OfflineGenerationRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("OnlineGenerationRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("QueueCap")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HabitatTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Habitats");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.HabitatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HabitatTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Aquarium",
                            Name = "Aquário"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Breeding",
                            Name = "Ninho"
                        });
                });

            modelBuilder.Entity("Vivarium.Core.Domain.ItemDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("EffectJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("PricePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceSoft")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ItemDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Filter",
                            EffectJson = "{\"restoreMaintenance\":100}",
                            Key = "filter_basic",
                            Name = "Filtro",
                            PriceSoft = 20m
                        },
                        new
                        {
                            Id = 2,
                            Category = "AutoFilter",
                            EffectJson = "{\"autoFilter\":true}",
                            Key = "auto_filter",
                            Name = "Filtro Automático",
                            PriceSoft = 500m
                        },
                        new
                        {
                            Id = 3,
                            Category = "HabitatUpgrade",
                            EffectJson = "{\"capacityDelta\":1}",
                            Key = "tank_upgrade",
                            Name = "Expansão do Tanque",
                            PriceSoft = 50m
                        });
                });

            modelBuilder.Entity("Vivarium.Core.Domain.MarketListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatureInstanceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceSoft")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreatureInstanceId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.ToTable("MarketListings");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseSpriteKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("HabitatTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("HabitatTypeId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSpriteKey = "fish_base_gray",
                            HabitatTypeId = 1,
                            Name = "Tetra Base"
                        });
                });

            modelBuilder.Entity("Vivarium.Core.Domain.TraitWeightConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("TraitCategory")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "PartType", "TraitCategory", "Version");

                    b.ToTable("TraitWeightConfigs");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.TransactionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatureInstanceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CurrencyTypeId")
                        .HasColumnType("integer");

                    b.Property<long?>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ToUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.UserInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ItemDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId");

                    b.HasIndex("UserId", "ItemDefinitionId")
                        .IsUnique();

                    b.ToTable("UserInventories");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.VipSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("VipSubscriptions");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.WalletBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("UserId", "CurrencyTypeId")
                        .IsUnique();

                    b.ToTable("WalletBalances");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.BreedingSlot", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.CreatureInstance", "ChildCreature")
                        .WithMany()
                        .HasForeignKey("ChildCreatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vivarium.Core.Domain.Habitat", "Habitat")
                        .WithMany()
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.CreatureInstance", "ParentA")
                        .WithMany()
                        .HasForeignKey("ParentAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.CreatureInstance", "ParentB")
                        .WithMany()
                        .HasForeignKey("ParentBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildCreature");

                    b.Navigation("Habitat");

                    b.Navigation("ParentA");

                    b.Navigation("ParentB");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.CreatureInstance", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.Habitat", "Habitat")
                        .WithMany()
                        .HasForeignKey("HabitatId");

                    b.HasOne("Vivarium.Core.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.CreatureInstance", "ParentA")
                        .WithMany()
                        .HasForeignKey("ParentAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vivarium.Core.Domain.CreatureInstance", "ParentB")
                        .WithMany()
                        .HasForeignKey("ParentBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vivarium.Core.Domain.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitat");

                    b.Navigation("Owner");

                    b.Navigation("ParentA");

                    b.Navigation("ParentB");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.GenerationQueueItem", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.Habitat", "Habitat")
                        .WithMany()
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitat");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.Habitat", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.HabitatType", "HabitatType")
                        .WithMany()
                        .HasForeignKey("HabitatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitatType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.MarketListing", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vivarium.Core.Domain.CreatureInstance", "CreatureInstance")
                        .WithMany()
                        .HasForeignKey("CreatureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("CreatureInstance");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.Species", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.HabitatType", "HabitatType")
                        .WithMany()
                        .HasForeignKey("HabitatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitatType");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.TraitWeightConfig", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.UserInventory", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.ItemDefinition", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.VipSubscription", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivarium.Core.Domain.WalletBalance", b =>
                {
                    b.HasOne("Vivarium.Core.Domain.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivarium.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyType");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
